### ISSUE TITLE
onnx转换rknn问题

### ISSUE THREAD

**Issue by twd19990423** [YaoQ/plate-detection-RK3588#1]
请教大佬，车牌识别字符部分onnx转换rknn怎么做到转出双分支，我的onnx两个output
![image](https://github.com/user-attachments/assets/980a7636-a652-4601-b624-10b92048d276)
但是导出onnx只有字符识别分支，没有颜色分支
![image](https://github.com/user-attachments/assets/5bec14ae-4c50-475c-abf2-c3e78bd5b5eb)
能发一下您的转换rknn的脚本吗 万分感谢！！！！

**Comment by AI-LLM2** [comment]
请问这个问题解决了吗？
